## Sentiment Analysis on Movies Review.

In [211]:
import pandas as pd 
import numpy as np

### Load the dataset.

In [212]:
review_df = pd.read_csv('../Datasets/IMDB Dataset.csv')

In [213]:
review_df.sample(5)

                                                  review sentiment
14596  Although the plot was a bit sappy at times, an...  positive
38971  I saw the first House of the Dead and expected...  negative
40214  I have been a rabid Star Trek fan since 1966. ...  negative
20406  "The Blob" qualifies as a cult sci-fi film not...  positive
15142  Jefferey dahmer was one sick guy. There's not ...  negative

In [214]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [215]:
review_df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

### Text Cleaning. 

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [216]:
review_df = review_df.sample(1000)

In [217]:
# make 0 and 1 in the output columns(sentiment). 
review_df['sentiment'].replace({'positive' : 1, 'negative' : 0}, inplace = True)

C:\Users\Mohd Uzaif\AppData\Local\Temp\ipykernel_20372\3937663904.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  review_df['sentiment'].replace({'positive' : 1, 'negative' : 0}, inplace = True)
C:\Users\Mohd Uzaif\AppData\Local\Temp\ipykernel_20372\3937663904.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  review_df['sentiment'].replace({'positive' : 1, 'negative' : 0}, inplace = True)

In [218]:
review_df.head()

                                                  review  sentiment
7096   For those with access to the BBC or the CBC, t...          1
36420  About the movie itself, there are ample commen...          0
45464  044: The Big Trail (1930) - released 10/24/193...          1
38149  Barbara Stanwyck plays Lily Powers. She's a wa...          1
12155  Thanks to Kevin Smith, a bunch of geeks are ru...          1

In [219]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', review_df.iloc[2].review)

'044: The Big Trail (1930) - released 10/24/1930; viewed 4/5/06.BIRTHS: Richard Harris, Harold Pinter, Robert Atkins.DOUG: In Hollywood, Raoul Walsh unveiled his latest film, The Big Trail, a western about the trek west across the frontier, starring up-and-coming 23-year-old actor John Wayne. In 1930, we are seeing many "firsts" but few "bests." Besides the first John Wayne film, we have here the first widescreen film (although we only watched the full-frame version). Interestingly, the decision to film in widescreen was essentially the same reason that widescreen became popular later: to compete with television, which hadn\'t yet appeared commercially but was still an emerging curiosity. All the same, this film was extremely good, giving us a harrowing look at the trek to Oklahoma. The opening title cards let us know that this is a western of the most traditional kind, about America, about the land, who should live on it, etc., and is an excellent demonstration of that. Walsh gives us some astonishing visuals of the wagon company out in the wilderness (when they reach a cliff, they must rope each wagon down one by one), and we also get a revenge subplot involving Wayne pursuing the man who killed one of his friends (I seem to recall something similar in Stagecoach). Wayne\'s tough cowboy routine is at least partly there, and would surely evolve further in subsequent films. Since this film is representing all of Wayne\'s early 30\'s work for the Odyssey, we will not see his face again until Stagecoach, but once we do, we will keep seeing him to the end of the Odyssey and beyond.KEVIN: Ah, our first sound western, and John Wayne\'s first starring role. It\'s Raoul Walsh\'s The Big Trail. This review will be short, since it\'s been weeks since I watched it. I enjoyed this movie, but it was far from a masterpiece. The mostly predictable adventure had a few surprises, like when the brains of the bad guys, Red Flack (Tyrone Power Sr. in his last role) is killed half way through; I thought he would be the boss at the end, but that ended up being Bill Thorpe (Ian Keith). I remember that I didn\'t like the way Breck (Wayne) kills Thorpe and exacts revenge at the end. I understood that that\'s what he was meant to do in the story, but I really didn\'t like his reasoning when he tells Ruth why he has to do it. I think he had a far greater responsibility to the hundreds of settlers he was leading through the harsh west.Last film viewed: Animal Crackers (1930). Last film chronologically: Soup to Nuts (1930). Next film: L\'Age D\'or (1930).'

In [220]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [221]:
review_df['review']=review_df['review'].apply(clean_html)

In [222]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [223]:
review_df['review']=review_df['review'].apply(convert_lower)

In [224]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [225]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [226]:
review_df['review']=review_df['review'].apply(remove_special)

In [227]:
# Remove the stop words
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Mohd
[nltk_data]     Uzaif\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [228]:
stop_words = set(stopwords.words('english')) 
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [229]:
# function to remove the stop words. 
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return " ".join(filtered_words)

In [230]:
review_df['review'] = review_df["review"].apply(remove_stopwords)

In [231]:
review_df.head()

                                                  review  sentiment
7096   access bbc cbc proved spectacular like battles...          1
36420  movie ample comments wanted say something germ...          0
45464  044 big trail 1930 released 10 24 1930 viewed ...          1
38149  barbara stanwyck plays lily powers waitress fa...          1
12155  thanks kevin smith bunch geeks running around ...          1

In [232]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [233]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [234]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [235]:
# apply the stemwords. 
review_df['review']=review_df['review'].apply(stem_words)

In [236]:
review_df

                                                  review  sentiment
7096   [a, c, c, e, s, s,  , b, b, c,  , c, b, c,  , ...          1
36420  [m, o, v, i, e,  , a, m, p, l, e,  , c, o, m, ...          0
45464  [0, 4, 4,  , b, i, g,  , t, r, a, i, l,  , 1, ...          1
38149  [b, a, r, b, a, r, a,  , s, t, a, n, w, y, c, ...          1
12155  [t, h, a, n, k, s,  , k, e, v, i, n,  , s, m, ...          1
...                                                  ...        ...
6438   [a, d, d, i, c, t, i, v, e,  , s, e, r, i, e, ...          1
12026  [e, v, e, n,  , r, e, m, o, t, e, l, y,  , f, ...          0
32501  [h, o, l, d, s,  , t, r, u, e,  , o, r, i, g, ...          1
5805   [h, e, l, p,  , t, h, i, n, k,  , b, e, h, i, ...          0
9814   [w, e, l, l,  , l, e, t,  , s, t, a, r, t,  , ...          0

[1000 rows x 2 columns]

In [237]:
# Join back
def join_back(list_input):
    return " ".join(list_input)

In [238]:
review_df['review']=review_df['review'].apply(join_back)

In [239]:
review_df.head()

                                                  review  sentiment
7096   a c c e s s   b b c   c b c   p r o v e d   s ...          1
36420  m o v i e   a m p l e   c o m m e n t s   w a ...          0
45464  0 4 4   b i g   t r a i l   1 9 3 0   r e l e ...          1
38149  b a r b a r a   s t a n w y c k   p l a y s   ...          1
12155  t h a n k s   k e v i n   s m i t h   b u n c ...          1

In [241]:
X=review_df.iloc[:,0:1].values

In [242]:
X.shape

(1000, 1)

In [244]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=500)

In [ ]:
X = cv.fit_transform(review_df['review']).toarray()

In [247]:
y=review_df.iloc[:,-1].values

In [248]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0])

In [249]:
# X,y
# Training set
# Test Set(Already know the result) 


# and then apply. 
# from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB