In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('../Datasets/play_tennis.csv')

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [8]:
# these are the joint probability 
pd.crosstab(df['outlook'], df['play'], normalize='all')

play            No       Yes
outlook
Overcast  0.000000  0.285714
Rain      0.142857  0.214286
Sunny     0.214286  0.142857

In [9]:
# these are the marginal and joint probability 
pd.crosstab(df['outlook'], df['play'], normalize='all', margins=True)

play            No       Yes       All
outlook
Overcast  0.000000  0.285714  0.285714
Rain      0.142857  0.214286  0.357143
Sunny     0.214286  0.142857  0.357143
All       0.357143  0.642857  1.000000

In [10]:
# these are the conditional probability 
pd.crosstab(df['outlook'], df['play'], normalize='columns')

play       No       Yes
outlook
Overcast  0.0  0.444444
Rain      0.4  0.333333
Sunny     0.6  0.222222

In [20]:
# how it calculate the probabilites and save them as dictionary. 
pd.crosstab(df['outlook'], df['play'], normalize='columns').stack().to_dict()

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222}

In [21]:
# for all the columns/features. 
final_prob = {} 
for column in ['outlook', 'temp', 'humidity', 'wind']: 
    final_prob.update(pd.crosstab(df[column], df['play'], normalize='columns').stack().to_dict())

In [22]:
final_prob

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222,
 ('Cool', 'No'): 0.2,
 ('Cool', 'Yes'): 0.3333333333333333,
 ('Hot', 'No'): 0.4,
 ('Hot', 'Yes'): 0.2222222222222222,
 ('Mild', 'No'): 0.4,
 ('Mild', 'Yes'): 0.4444444444444444,
 ('High', 'No'): 0.8,
 ('High', 'Yes'): 0.3333333333333333,
 ('Normal', 'No'): 0.2,
 ('Normal', 'Yes'): 0.6666666666666666,
 ('Strong', 'No'): 0.6,
 ('Strong', 'Yes'): 0.3333333333333333,
 ('Weak', 'No'): 0.4,
 ('Weak', 'Yes'): 0.6666666666666666}